name: CI

on:
  push:
    branches:
      - main
      - dev

jobs:
  sast_scan:
    name: Bandit Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Python setup
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install Bandit
        run: pip install bandit

      - name: Run Bandit
        run: bandit -r . -f json -o bandit.json

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: bandit-scan
          path: bandit.json
  
  image_scan:
    name: Build container
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Docker
        uses: docker-practice/actions-setup-docker@v1
        with:
          docker_version: '20.10.7'

      - name: Build
        run: docker build -f Dockerfile -t myapp:latest .